# <string>
#
# Path (relative to the location of this file, or absolute) to the
# hledger journal.  Optional.
journal_file: ~/hledger.journal

# <string>
#
# The default commodity.  Currently only postings which have a value
# in this commodity are supported.  Let's say your default commodity
# is "£", this means all of your postings must have one of these three
# forms:
#
#   - "account  £xxx"
#   - "account  xxx @ £yyy"
#   - "account  xxx @@ £yyy"
#
# So if you have non-default commodities, all you can do is buy or
# sell them with your default commodity.  Postings which do not
# mention your default commodity at all will just cause the server to
# throw an error, sorry!
default_commodity: £

# The web server configuration.
http:
  # <int>
  #
  # Port to listen on.
  port: 5000
  # <string>
  #
  # Path (relative to the location of this file, or absolute) to
  # static assets.
  static_dir: ./web

# The account tree configuration.
tree:
  # <string OR [string]>
  #
  # These accounts are considered asset accounts.  "*" may be used as
  # a wildcard.  Defaults to "assets:*".
  assets: assets:*:*

  # <string OR [string]>
  #
  # These accounts are considered to be equity accounts.  "*" may be
  # used as a wildcard.  Defaults to "equity:*".
  equity: equity:*

  # <string OR [string]>
  #
  # These accounts are considered to be expense accounts.  "*" may be
  # used as a wildcard.  Defaults to "expenses:*".
  expenses: expenses:*

  # <string OR [string]>
  #
  # These accounts are considered to be income accounts.  "*" may be
  # used as a wildcard.  Defaults to "income:*".
  income: income:*

  # <string OR [string]>
  #
  # These accounts are considered to be liability accounts.  "*" may
  # be used as a wildcard.  Defaults to "liabilities:*".
  liabilities: liabilities:*

  # <string OR [string]>
  #
  # These accounts are considered to be envelope budget accounts.  "*"
  # may be used as a wildcard.  Defaults to "budget:*".
  budget: assets:cash:santander:current:budget:*

# <string -> (account OR string)>
#
# Information about accounts.  Keys are account names.  Each entry has
# four fields:
#
#  - name: <string> a nice name.  Defaults to the bit after the last
#    ":" in titlecase.
#
#  - url: <string> a URL for further information.  Optional.
#
#  - category: <string> where to file this in the balance sheet.  Has
#    the following defaults:
#    - assets:      "Current"
#    - equity:      "Start of Period"
#    - liabilities: "Current"
#    - income:      "End of Period"
#    - expenses:    "End of Period"
#
#    Those assets and liabilities filed under "Current" are used in
#    the net worth calculation in the sidebar.
#
# Just giving the account name as a string is allowed as a short-hand,
# which leaves all the other fields at their default values.
#
accounts:
  "assets:cash:paypal": PayPal
  "assets:cash:santander:current:budget:tfp food": TFP Food
  "assets:cash:santander:esaver": eSaver
  "assets:cash:santander:esaver:rainyday": Rainy Day
  "assets:investments:cavendish":
    name: Cavendish Online
    category: Investments
  "income:pta": PTA
  "liabilities:slc":
    name: Student Loans Company
    category: Long Term

# <string -> (commodity OR string)>
#
# Information about commodities.  Keys are commodity names.  Each
# entry has three fields:
#
#  - name: <string> a nice name.  Defaults to the commodity symbol.
#
#  - url: <string> a URL for further information.  Optional.
#
#  - allocation: <string OR (string -> int)> what this commodity is
#    made up of.  If given as an object, the commodity is split into
#    parts weighted by the given ints.  Defaults to "Cash".
#
# Just giving the commodity name as a string is allowed as a
# short-hand, which leaves all the other fields at their default
# values.
#
commodities:
  MHMIA:
    name: Marlborough UK Micro-Cap
    url:  https://markets.ft.com/data/funds/tearsheet/summary?s=gb00b8f8yx59:gbx
    allocation: Equities

  NPMKA:
    name: Neptune Emerging Markets
    url:  https://markets.ft.com/data/funds/tearsheet/summary?s=gb00b8j6sv12:gbp
    allocation: Equities

  VALEA:
    name: Vanguard LifeStrategy 20%
    url:  https://markets.ft.com/data/funds/tearsheet/summary?s=gb00b4nxy349:gbp
    allocation:
      Equities: 80
      Bonds:    20

  WIFCA:
    name: CF Woodford Income Focus
    url:  https://markets.ft.com/data/funds/tearsheet/summary?s=GB00BD9X6D51:gbx
    allocation: Equities
