# The web server:
http:
  # <int>
  # Port to listen on:
  port: 5000
  # <string>
  # Path (relative to the location of this file, or absolute) to
  # static assets:
  static_dir: ./web

# <[account]>
# The assets charts:
assets:
  - name: Cavendish Online
    # <[subaccount]>
    breakdown:
    - name: Marlborough UK Micro-Cap
      # <string>
      # The hledger account
      account: assets:cavendish:MHMIA
      # <string> OR <string -> int>
      # The type of asset stored in this account.  Think "Cash",
      # "Equities", "Bonds", "Property", ...
      # (optional, defaults to "Cash")
      tag: Equities
      # <string>
      # The category this goes under in the balance sheet
      # (optional, defaults to "Current")
      balance_tag: Investments
      # <string>
      # Link to more information (optional)
      url: https://markets.ft.com/data/funds/tearsheet/summary?s=gb00b8f8yx59:gbx

    - name: Neptune Emerging Markets
      account: assets:cavendish:NPMKA
      tag: Equities
      balance_tag: Investments
      url: https://markets.ft.com/data/funds/tearsheet/summary?s=gb00b8j6sv12:gbp

    - name: Vanguard LifeStrategy 20%
      account: assets:cavendish:VALEA
      # If the tag is an object, the value in the account is split
      # accordingly.
      tag:
        Equities: 20
        Bonds:    80
      balance_tag: Investments
      url: https://markets.ft.com/data/funds/tearsheet/summary?s=gb00b4nxy349:gbp

  - name: Nationwide
    breakdown:
      - account: assets:nationwide

  - name: Santander
    breakdown:
      - name: Main
        account: assets:santander:main
      - name: eSaver
        account: assets:santander:esaver

# <[account]>
# The liabilities:
liabilities:
  - name: Current
    # <[subaccount]>
    # The behaviour is slightly different to asset breakdowns:
    #  - 'tag' is ignored.
    #  - 'balance_tag' defaults to the name of the overall account
    #    ("Current" here).
    breakdown:
      - name: Overdraft
        account: liabilities:overdraft

  - name: Long Term
    breakdown:
      - name: Student Loan
        account: liabilities:slc

# <account rules>
# The income accounts:
income:
  # Account rules are one of:
  #  - a list of account rules (tried in order and the first match used).
  #  - a key "only" with an object whose keys are accounts and values names.
  #  - a key "simple" with a prefix to match and remove.
  #  - a null, which matches nothing.
  - only:
      "income:pta": PTA
  - simple: income

# <account rules>
# The budget accounts:
budget:
  simple: assets:santander:main:budget

# <account rules>
# The expense accounts:
expenses:
  simple: expenses

# <account rules>
# The equity accounts:
equity:
  simple: equity
