http:
  port: 5000
  static_dir: ./static

accounts:
  assets:
    only:
      "assets:cavendish":        Cavendish Online
      "assets:nationwide":       Nationwide
      "assets:santander:esaver": Santander (eSaver)
      "assets:santander:main":   Santander (main)
  income:
    try:
      - only:
          "income:pta": PTA
      - simple: income
  budget:
    simple: assets:santander:main:budget
  expenses:
    simple: expenses

assets:
  "assets:cavendish:MHMIA":
    name: Marlborough UK Micro-Cap
    tag: Funds
  "assets:cavendish:NPMKA":
    name: Neptune Emerging Markets
    tag: Funds
  "assets:cavendish:VALEA":
    name: Vanguard LifeStrategy 20%
    tag: Funds
  "assets:nationwide":
    tag: Cash
  "assets:santander":
    name: Santander
    tag: Cash
