executables:
  webui:
    main: Main.hs
    dependencies:
      - base
      - aeson
      - containers
      - hledger-lib
      - http-types
      - text
      - time
      - wai
      - wai-middleware-static
      - warp
