executables:
  backend:
    main: Main.hs
    other-modules:
      - Config
      - Report
      - Template
    dependencies:
      - base
      - aeson
      - containers
      - data-default-class
      - directory
      - filepath
      - ginger
      - hledger-lib
      - http-types
      - text
      - time
      - unordered-containers
      - wai
      - wai-middleware-static
      - warp
      - yaml
    ghc-options: -Wall
